lib/simctl.js

this PR adds wrappers around the `install`, `uninstall` and `launch` commands in simctl.  I'll follow up with a PR in appium to use these methods properly in the Simulator class.  
I didn't write tests for these because I thought I'd chat with you about it first - to test these I'd need to find some kind of 'hello world' app that i'll need to include in the source code to be able to install on a simulator, i'm not sure if this will even work if the simulator is not yet booted (so we'll need to shell out to instruments probably).  How do you want to proceed?

add installation/removal/launching of apps via simctl

---

lib/simctl.js

Allows us to run WebDriverAgent (or any general executable) through simctl.

Add support for `xcrun simctl spawn`.

---

package.json

Lodash is imported in `lib/simctl.js` and thus we need to move it from devDependencies to dependencies.

Move lodash from devDependencies to dependencies

---

lib/simctl.js

Some small style fixes. But the meat is (a) removing retry logic in `deleteDevice`, and (b) adding logic to `createDevice` to wait for the new device to get out of the `Creating` state.
@Jonahss

Add wait in create device

---

lib/simctl.js

Remove a log line that is often repeated over and over again, as the function is called in a retry loop. The calling code can log more useful information.

Remove repeated log line

---

lib/simctl.js
test/simctl-specs.js

Rather than hardcoding it, allow the calling code to say how long it should wait.

Allow configurable timeouts on create and erase

---

lib/simctl.js

Tiny tweak to regexp to allow for two words in the state. This occurs when a device is shutting down (state is `Shutting Down`).

State might be two words

---

lib/simctl.js

Only having it at the level of the parent array makes processing more difficult in other places.

Add sdk to device list for easy access in other systems

---

lib/simctl.js

This will be needed to finish new simulator startup flow PR for appium-xcuitest-driver

Add wrapper over terminate and getAppContainer calls for simctl

---

lib/simctl.js

Set up the machinery for allowing an optional parameter to a method to block logging. At this point the only need for this is `getAppContainer`, which _should_ throw an error if there is no app container (i.e., if the app is not installed) and so we don't want logging, since that signals to the user that there was a problem.
In future other methods may have valid reasons to do the same. Right now they will function as they always have.

Allow getAppContainer to run without logging

---

lib/simctl.js
test/simctl-specs.js

Hi!
I've started Appium today and got an error:
```bash
-------------------------------------
Error while executing tests:
A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.2.1. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.
-------------------------------------
Stack:
{ status: 33,
type: 'SessionNotCreatedException',
message: 'A new session could not be created.',
orgStatusMessage: 'A new session could not be created. Details: Appium\'s IosDriver does not support xcode version 8.2.1. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.' }
-------------------------------------
```
I thought looks like one of deps was updated and it was `node-simctl`.
New …

Add test and fix for getDevices function

---

lib/simctl.js

If xcode has a sim with a patch version (like Xcode 8.3.3, which has iOS 10.3.1 instead of 10.3) creating a device will fail.

Add method to get runtime for platform

---

lib/simctl.js

This will be extremely useful for iOS11, since now simctl actually controls headless simulation server and can control multiple virtual devices without UI.

Add boot command to the list of API wrappers

---

.travis.yml
lib/simctl.js

`bootDevice` was added as a method but not exported. Eslint failed.
Added eslint to Travis config so even if a developer skips the pre-commit hooks, the build will fail.

Fix bootDevice and add eslint to travis

---

lib/simctl.js

I observe that it is sometimes unclear to users why the platformVersion they set in capabilities does not match any of the available Simulators. This PR should improve the situation by printing a better error message.

Improve the error message for missing Simulator SDK

---

package.json
test/simctl-e2e-specs.js

Add a gulp task for fixing eslint. And fix the arrow functions in mocha.
appium/appium#10016

Get rid of arrow functions in mocha aparatus

---

lib/simctl.js

I've noticed that `bootstatus` command makes the process to wait forever if one tries to start it for Simulator, which exists, but has not been booted. This PR makes sure the waiting process is killed after the timeout expires.

Make sure the boot monitoring process is properly killed after the timeout

---

.travis.yml
lib/simctl.js
package.json
test/fixtures/devices-simple.json
test/fixtures/devices-with-unavailable-simple.json
test/fixtures/devices-with-unavailable.json
test/fixtures/devices.json
test/simctl-e2e-specs.js
test/simctl-specs.js

There are cases where the platform and sdk are listed as we expect (e.g., `iOS 12.2`) and cases where they are in a different form (e.g., `com.apple.CoreSimulator.SimRuntime.iOS-12-2`). This PR makes accommodations for that variance.
It also puts the platform into the simulator info object, so that downstream consumers know what sort of device it is.
And finally, it adds unit tests for the JSON-based parsing of devices.

Adjust getDevices and add unit tests

---

.travis.yml
lib/simctl.js
package.json
test/simctl-e2e-specs.js
test/simctl-specs.js

After installing Xcode 10.2, the creating format should be `com.apple.CoreSimulator.SimRuntime.iOS-XX-X` instead of `XX.X`. The format is the same even we change the xcode version as 10.1 with `xcode-select`. Thus, I follow this logic, try to call the new format once and if an error raises, try to call old format.
- new format
```
$ xcrun simctl create 'iPhone XS 2'  com.apple.CoreSimulator.SimDeviceType.iPhone-8 com.apple.CoreSimulator.SimRuntime.iOS-12-1
7CD85972-2FB1-4236-B4E9-A2017AB00959
```
- old format
```
$ xcrun simctl create 'iPhone XS 2'  com.apple.CoreSimulator.SimDeviceType.iPhone-8 12.1
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=162):
Incompatible device
```
Will update xcuitest-driver after this like …

fix creating simulators for new format

---

lib/simctl.js
package.json
test/simctl-specs.js

Fixes the exception when `getCommandLineToolsVersion` is unable to retrieve CLT version. Based on https://github.com/appium/appium-xcode/pull/48

Fix Command Line Tools version verification

---

lib/simctl.js
test/simctl-e2e-specs.js
test/simctl-specs.js

Fixes problems with https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=5507
Driver Specs were not working because it wasn't parsing correctly. Tries using `--json` flag first.

fix: Use --json flag to get runtime

---

.travis.yml
lib/simctl.js
package.json
test/simctl-e2e-specs.js
test/simctl-specs.js

Make sure that we can create simulators when the platform version and runtimes are different (which is mostly to say, when there is a patch version of a sim)
So, if `xcrun simctl list runtimes` returns:
```
== Runtimes ==
iOS 9.3 (9.3 - 13E233) - com.apple.CoreSimulator.SimRuntime.iOS-9-3
iOS 10.3 (10.3.1 - 14E8301) - com.apple.CoreSimulator.SimRuntime.iOS-10-3
iOS 11.0 (11.0.1 - 15A8401) - com.apple.CoreSimulator.SimRuntime.iOS-11-0
iOS 11.1 (11.1 - 15B87) - com.apple.CoreSimulator.SimRuntime.iOS-11-1
iOS 11.2 (11.2 - 15C107) - com.apple.CoreSimulator.SimRuntime.iOS-11-2
iOS 11.3 (11.3 - 15E217) - com.apple.CoreSimulator.SimRuntime.iOS-11-3
iOS 11.4 (11.4 - 15F79) - com.apple.CoreSimulator.SimRuntime.iOS-11-4
iOS 12.0 (12.0 - 16A366) - com.apple.CoreSimulator.SimRuntime.iOS-12-0
iOS 12.1 …
```

refactor: simplify createDevice logic

---

lib/simctl.js
package.json
test/simctl-e2e-specs.js

Check `major.minor` versions of platform and runtime, rather than raw versions.

fix: properly match version from json

---

lib/simctl.js

https://developer.apple.com/documentation/xcode_release_notes/xcode_11_4_beta_release_notes?language=objc

feat: Add support for simctl features since Xcode SDK 11.4

---

.travis.yml
test/simctl-e2e-specs.js

This PR address a minor issue on e2e test that I found while playing around with the project. 
The const DEVICE_NAME was set to iPhone 6 and tests were failing locally as this is simulator is not available on a cutting edge SimRuntime version (like 13.5). This update also streamlines with the device name used on the CI jobs.

fix: bump DEVICE_NAME const on e2s tests to iPhone X

---

lib/logger.js
lib/simctl.js
lib/subcommands/bootstatus.js
lib/subcommands/io.js
lib/subcommands/keychain.js
lib/subcommands/push.js
package.json
test/simctl-e2e-specs.js

`appium-support` is big and it adds unnecessary overhead if this module is imported by third-parties

chore: Avoid appium-support imports

---

lib/subcommands/getenv.js

Error logging for this endpoint is redundant as we sometimes expect it to fail and this creates excessive and confusing log records

chore: disable explicit errors logging for getenv calls

---

lib/logger.js
lib/simctl.js

With the current implementation the log message is printed as prefix, which is wrong

chore: Patch the npm logger properly

---

lib/logger.js
lib/simctl.js
lib/subcommands/boot.js
lib/subcommands/create.js
lib/subcommands/list.js
lib/subcommands/shutdown.js

It turns out the previous implementation was changing the logger instance globally, which enforced the `simctl` prefix to be added everywhere

fix: Avoid global logger patching

---

.azure-pipelines.yml

We no longer support Xcode 10, so simply can drop it

ci: drop Xcode 10

---

package.json

Needed `build/index.js` to load it as main

fix: add missing build/index

---

lib/simctl.js

`Simctl` has default timeout to run `exec` by `teen_process`, but the `exec` method in `Simctl` does not have individual timeout option. It makes sense to let caller to set `timeout` per command and the constructor's timeout is default value for the `Simctl` object wide.
One typical usage is https://github.com/appium/appium-xcuitest-driver/pull/2461

feat: add timeout option for exec

---

lib/subcommands/ui.js

To support https://github.com/appium/appium-xcuitest-driver/issues/2519
Example output:
```
kazu $ xcrun simctl ui "iPhone 16 Plus" content_size
large
kazu $ xcrun simctl ui "iPhone 16 Plus" content_size increment
kazu $ xcrun simctl ui "iPhone 16 Plus" content_size
extra-large
```
```
kazu $ xcrun simctl ui "iPhone 16 Plus" increase_contrast
disabled
kazu $ xcrun simctl ui "iPhone 16 Plus" increase_contrast enabled
kazu $ xcrun simctl ui "iPhone 16 Plus" increase_contrast
enabled
```
Validation for the input will be in the xcuitest driver side similar to appearance https://github.com/appium/appium-xcuitest-driver/blob/1cbd80eb516740945208c049c278aaaa2d014052/lib/commands/appearance.js#L14-L16

feat: add content_size and increase_contrast commands for ui
