- .travis.yml
- README.md
- lib/simctl.js
- package.json
- test/simctl-specs.js
Clean up dependencies and tests.
> First pass at cleanup

- lib/simctl.js
Just a little more information for logging purposes.
> Add command name to error message

- lib/simctl.js
We're having problems elsewhere in command execution, but it is not possible to see what the actual command is.
> Add command logging

- lib/simctl.js
- test/simctl-specs.js
Logging added to solve a problem elsewhere.
Also bumped timeout on erase device test, hopefully improving its flakiness.
> Remove extra logging

- lib/simctl.js
And slow down retries of erase.
> Retry launch if it fails

- lib/simctl.js
There is a lot of complexity in trying to parse the device list. Use the JSON output instead.
> Use JSON list of devices

- lib/simctl.js
- package.json
Move off deprecated `appium-logger`.
> Move to logger from appium-support

- .eslintrc
- lib/simctl.js
- package.json
- test/simctl-specs.js
A little more involved than normal since we do type annotation here.
> Add eslint and fix issues

- lib/simctl.js
- package.json
- test/simctl-specs.js
Looking forward to enable this functionality in xcuitest driver 😻
> Add a possibility to set and print pasteboard content

- test/simctl-specs.js
> Fix mocha timeout value

- lib/simctl.js
- test/simctl-e2e-specs.js
It will be possible to add any media file to iOS Simulator with this
> Add a possibility to upload media

- lib/simctl.js
- test/simctl-e2e-specs.js
This should fix system apps detection on Simulator and should help to address issues similar to https://github.com/appium/appium/issues/9102
> Add the hidden appinfo subcommand

- lib/simctl.js
It is looking much nicer with documentation included 😻
> Add docstrings

- test/simctl-e2e-specs.js
Part of https://github.com/appium/appium/issues/10685
> Fix buffer usage

- .travis.yml
- lib/simctl.js
- test/simctl-e2e-specs.js
We want to be able to run tests against all types of devices. So we need to be able to get all types of devices.
> Add function to get list of device types

- lib/simctl.js
- test/simctl-e2e-specs.js
This will allow to provide fine-grained control over simulator booting process
> Implement the hidden bootstatus simctl command

- lib/simctl.js
https://github.com/appium/appium/issues/11892
> Add platform argument to getDevices call

- lib/simctl.js
> Fix version matching

- lib/simctl.js
https://developer.apple.com/forums/thread/13208
> feat: Add a possibility to provide a path to the given devices set

- lib/subcommands/io.js
- lib/subcommands/keychain.js
- lib/subcommands/push.js
- test/e2e/simctl-e2e-specs.js
Addresses https://github.com/appium/appium-xcuitest-driver/pull/1507#issuecomment-1445003073
cc @mwakizaka
> fix: Update rimraf and fs promises usage

- test/e2e/simctl-e2e-specs.js
should be merged after https://github.com/appium/node-simctl/pull/174
I didn't add tests for `addCertificate` command as we roughly cover it in https://github.com/appium/appium-xcuitest-driver/pull/1507
> test: add test for getScreenshot and pushNotification commands

- lib/simctl.js
- lib/subcommands/addmedia.js
- lib/subcommands/appinfo.js
- lib/subcommands/bootstatus.js
- lib/subcommands/create.js
- lib/subcommands/get_app_container.js
- lib/subcommands/getenv.js
- lib/subcommands/io.js
- lib/subcommands/launch.js
- lib/subcommands/list.js
- lib/subcommands/openurl.js
- lib/subcommands/pbcopy.js
- lib/subcommands/pbpaste.js
- lib/subcommands/spawn.js
- lib/subcommands/ui.js
https://github.com/appium/appium/issues/18966
> feat: Add a possibility to select architecture while executing xcrun commands
